F2_jsonpCallback_{{appid}}({
	{{#inlineScripts}}
	"inlineScripts":[{{{inlineScripts}}}],
	{{/inlineScripts}}
	"scripts":[
		{{{scripts}}}
	],
	{{#styles}}
	"styles":[
		{{{styles}}}
	],
	{{/styles}}
	"apps":[{
		"html":"{{{html}}}"
	}]
})